import { Injectable } from "@angular/core";

@Injectable({
    providedIn: 'root'
})

export class Doctypes {
    doctypes = {
        Episode: 'NP Patient Episode',
        Problem: 'NP Patient Problem',
        Patient: 'NP Patient',
        Appointment_Type: "NP Appointment Type",
        File_Type: "File Type",
        FileDoctype: "File",
        bodyPartDoctype: "NP PM Body Part",
        Comment: "Comment",
        Patient_Service_Assignment: "Patient Service Assignment",
        SDMM_Template: "SDMM Template",
        SDMM_Methods: "SDMM Methods",
        Warehouse: "Warehouse",
        Medical_User_Settings: "NP Medical User Settings",
        Consent_Form: "NP Consent Form",
        NP_Patient_Appointment: "NP Patient Appointment",
        Sales_Invoice: 'Sales Invoice',
        Medical_Department: "NP Medical Department",
        NP_Clinical_Procedure: "NP Clinical Procedure",
        NP_Patient_Encounter: "NP Patient Encounter",
        NP_External_Report: 'NP External Report',
        External_Report_Profile: 'NP External Report Profile',
        NP_Package_Subscription: 'NP Package Subscription',
        NP_Patient_Payor_Approval: 'NP Patient Payor Approval',
        NP_Lab_Test: "NP Lab Test",
        Medical_Code: 'NP Medical Code',
        Country: "Country",
        ToDo: 'ToDo',
        System_Settings: 'System Settings',
        NP_Package: "NP Package",
        Patient_Sick_Leave: "NP Patient Sick Leave",
        Problem_Type: 'NP Problem Type',
        Category: "Category",
        NP_Payor_Contract: 'NP Payor Contract',
        Item_Price: "Item Price",
        Allergy: 'Allergy',
        Prescription_Dosage: 'NP Prescription Dosage',
        Prescription_Duration: 'NP Prescription Duration',
        Route: 'NP Route',
        Healthcare_Practitioner_Level: 'NP Healthcare Practitioner Level',
        NP_Healthcare_Practitioner: 'NP Healthcare Practitioner',
        NP_Patient_Payor_Subscription: "NP Patient Payor Subscription",
        Company: "Company",
        NP_Procedure_Category: "NP Procedure Category",
        Healthcare_Service_Unit: 'NP Healthcare Service Unit',
        Inpatient_Record: 'NP Inpatient Record',
        Kiosk_Profile: 'NP Kiosk Profile',
        Language: 'Language',
        Consent_Form_Template: 'NP Consent Form Template',
        Practitioner_Event: 'NP Practitioner Event',
        Patient_Appointment_Waiting_List: 'Patient Appointment Waiting List',
        Outcome_Measures_Profile: 'Outcome Measures Profile',
        NP_Dental_Numbering_Systems: 'NP Dental Numbering Systems',
        Payer: "Payer",
        Appointment_Type_Kiosk: "NP Appointment Type Kiosk",
        Appointment_Type_Service_Item: "NP Appointment Type Service Item",
        // 
        medication_Template: "NP Medication Template",
        NP_Lab_Test_Template: 'NP Lab Test Template',
        Radiology_Procedure_Template: 'NP Radiology Procedure Template',
        Clinical_Procedure_Template: "NP Clinical Procedure Template",
        NP_Patient_Medication: "NP Patient Medication",
        Account: "Account",
        Price_List: "Price List",
        Campaign: "Campaign",
        NP_Requested_Appointment: "NP Requested Appointment",
        NP_Radiology_Template: "NP Radiology Template",
        NP_Patient_Radiology_Order: "NP Patient Radiology Order",
        NP_Nixpend_Healthcare_Settings: "NP Nixpend Healthcare Settings",
        NP_Patient_Category: "NP Patient Category",
        NP_Appointment_Order: "NP Appointment Order",
        NP_Patient_Record_Flag:"NP Patient Record Flag",
        POS_INVOICE:'POS Invoice',
        NP_Healthcare_Service_Unit:'NP Healthcare Service Unit',
        NP_Graph_Annotation_Category:'NP Graph Annotation Category',
        NP_Country: "NP Country",
        NP_PATIENT_FEEDBACK:"NP Patient Feedback",
        SDMM_Patient_Activities_Profile:"SDMM Patient Activities Profile",
        Activities_Profile_Table:"Activities Profile Table",
        NP_Episode_Sign_and_Symptoms:"NP Episode Sign and Symptoms",
        NP_Patient_History:"NP Patient History"

    }
}